cartesian_limits:
  max_trans_vel: 1
  max_trans_acc: 2.25
  max_trans_dec: -5
  max_rot_vel: 1.57

f_gantry_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - J1
      - J2
      - J4
      - J5
      - J6
      - J7
      - J8
      - J9
  gazebo_ros_control:
    pid_gains:
      J1: {p: 100, d: 0.001, i: 2, i_clamp: 1}
      J2: {p: 100, d: 0.001, i: 2, i_clamp: 1}
      # J3: {p: 100, d: 1, i: 1, i_clamp: 1}
      J4: {p: 100, d: 0.001, i: 2, i_clamp: 1}
      J5: {p: 100, d: 0.001, i: 2, i_clamp: 1}
      J6: {p: 100, d: 0.001, i: 2, i_clamp: 1}
      J7: {p: 10, d: 0.001, i: 2, i_clamp: 1}
      J8: {p: 10, d: 0.001, i: 2, i_clamp: 1}
      J9: {p: 10, d: 0.001, i: 2, i_clamp: 1}