controller_list:
  - name: /f_gantry_robot/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - J1
      - J2
      - J4
      - J5
      - J6
      - J7
      - J8
      - J9

f_gantry_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - J1
      - J2
      - J4
      - J5
      - J6
      - J7
      - J8
      - J9
  gazebo_ros_control:
    pid_gains:
      J1: {p: 100, d: 0.001, i: 2, i_clamp: 1}
      J2: {p: 100, d: 0.001, i: 2, i_clamp: 1}
      # J3: {p: 100, d: 1, i: 1, i_clamp: 1}
      J4: {p: 100, d: 0.001, i: 2, i_clamp: 1}
      J5: {p: 100, d: 0.001, i: 2, i_clamp: 1}
      J6: {p: 100, d: 0.001, i: 2, i_clamp: 1}
      J7: {p: 10, d: 0.001, i: 2, i_clamp: 1}
      J8: {p: 10, d: 0.001, i: 2, i_clamp: 1}
      J9: {p: 10, d: 0.001, i: 2, i_clamp: 1}









# controller_list:
#   - name: fake_gantry_controller
#     type: $(arg execution_type)
#     joints:
#       - J1
#       - J2
#       - J4
#       - J5
#       - J6
#       - J7
#       - J8
#       - J9
# initial:  # Define initial robot poses.
#   - group: gantry
#     pose: start