f_gantry_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - J1
      - J2
      - J4
      - J5
      - J6
      - J7
      - J8
      - J9
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      J1: {trajectory: 100, goal: 1}
      J2: {trajectory: 100, goal: 1}
      J4: {trajectory: 100, goal: 1}
      J5: {trajectory: 100, goal: 1}
      J6: {trajectory: 100, goal: 1}
      J7: {trajectory: 100, goal: 1}
      J8: {trajectory: 100, goal: 1}
    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_rate: 10

  gazebo_ros_control:
    pid_gains:
      J1: {p: 50, d: 30, i: 0.001, i_clamp: 1}
      J2: {p: 50, d: 30, i: 0.001, i_clamp: 1}
      # J3: {p: 100, d: 1, i: 1, i_clamp: 1}
      J4: {p: 100, d: 0.01, i: 0.001, i_clamp: 1}
      J5: {p: 100, d: 0.01, i: 0.001, i_clamp: 1}
      J6: {p: 100, d: 0.01, i: 0.001, i_clamp: 1}
      J7: {p: 1, d: 0, i: 0, i_clamp: 1}
      J8: {p: 1, d: 0, i: 0, i_clamp: 1}
      J9: {p: 1, d: 0, i: 0, i_clamp: 1}

controller_list:
  - name: /f_gantry_robot/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - J1
      - J2
      - J4
      - J5
      - J6
      - J7
      - J8
      - J9